# Generated by Django 2.2.3 on 2019-07-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('run_time', models.DurationField()),
                ('RTD1_start_temperature', models.FloatField()),
                ('RTD2_start_temperature', models.FloatField()),
                ('RTD1_end_temperature', models.FloatField()),
                ('RTD2_end_temperature', models.FloatField()),
                ('passornot', models.BooleanField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '高转速试验',
                'verbose_name_plural': '高转速试验',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='MotorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_PN', models.CharField(max_length=32)),
                ('motor_model', models.CharField(choices=[('M17P3-S-18AXYY', 'M17P3-S-18AXYY'), ('M24P4', 'M24P4')], max_length=32)),
                ('motor_code', models.CharField(max_length=32)),
                ('tester1', models.CharField(choices=[('Leon Chen', '陈晓文'), ('Tiegen Ji', '季铁根'), ('Sylvain Yu', '郁松林'), ('Jiliang Hong', '小洪'), ('Charles Li', '小李'), ('Brant Miao', '苗强')], max_length=32)),
                ('tester2', models.CharField(choices=[('Leon Chen', '陈晓文'), ('Tiegen Ji', '季铁根'), ('Sylvain Yu', '郁松林'), ('Jiliang Hong', '小洪'), ('Charles Li', '小李'), ('Brant Miao', '苗强')], max_length=32)),
                ('ambient_temperature', models.FloatField()),
                ('ambient_humidity', models.FloatField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('highspeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.HighSpeed')),
            ],
            options={
                'verbose_name': '电机信息',
                'verbose_name_plural': '电机信息',
                'ordering': ['c_time'],
            },
        ),
    ]
