# Generated by Django 2.2.3 on 2019-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highspeed',
            name='comment',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='comment',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='forward_direction',
            field=models.CharField(choices=[('clockwise', '顺时针'), ('anti-clockwise', '逆时针')], default='clockwise', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='inverter_type',
            field=models.CharField(choices=[('RMS-250DZ', 'RMS-250DZ')], default='RMS-250DZ', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='motor_poles',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='motor_type_options_eeprom',
            field=models.IntegerField(default='50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='phase_connection',
            field=models.CharField(choices=[('UVW to ABC', 'UVW to ABC'), ('UWV to ABC', 'UWV to ABC')], default='UVW to ABC', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='resolver_poles',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
    ]
