# Generated by Django 2.2.3 on 2019-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_bemf_calibration_continuous_currentvstorque_highspeed_insulation_motorinfo_shortcircuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemf',
            name='motor_PN',
            field=models.CharField(default='no', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemf',
            name='motor_code',
            field=models.CharField(default='no', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemf',
            name='motor_model',
            field=models.CharField(default='no', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='motor_PN',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='motor_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='motor_model',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='continuous',
            name='motor_PN',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='continuous',
            name='motor_code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='continuous',
            name='motor_model',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentvstorque',
            name='motor_PN',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentvstorque',
            name='motor_code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentvstorque',
            name='motor_model',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highspeed',
            name='motor_PN',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highspeed',
            name='motor_code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highspeed',
            name='motor_model',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insulation',
            name='motor_PN',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insulation',
            name='motor_code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insulation',
            name='motor_model',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcircuit',
            name='motor_PN',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcircuit',
            name='motor_code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcircuit',
            name='motor_model',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
