# Generated by Django 2.2.3 on 2019-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20190712_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='inverter_type',
            field=models.CharField(choices=[('RMS PM250DZ', 'RMS PM250DZ')], max_length=32),
        ),
    ]
