# Generated by Django 2.2.3 on 2019-07-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20190712_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highspeed',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='highspeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.HighSpeed'),
        ),
    ]
