# Generated by Django 2.2.3 on 2019-07-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20190712_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorinfo',
            name='highspeed',
        ),
        migrations.AddField(
            model_name='highspeed',
            name='motorinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='inverter_type',
            field=models.CharField(choices=[('RMS PM250DZ', 'RMS PM250DZ'), ('RMS PM100', 'RMS PM100'), ('EMSISO EM500', 'EMSISO EM500'), ('EMSISO EM100', 'EMSISO EM100'), ('EMSISO EM200', 'EMSISO EM200')], max_length=32),
        ),
    ]
