# Generated by Django 2.2.3 on 2019-11-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20191111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvstorque',
            name='torque_command',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentvstorque',
            name='torque_measured',
            field=models.FloatField(null=True),
        ),
    ]
