# Generated by Django 2.2.3 on 2019-07-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20190712_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highspeed',
            name='motorinfo',
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='highspeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.HighSpeed'),
        ),
    ]
