# Generated by Django 2.2.3 on 2019-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20190712_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorinfo',
            name='highspeed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.HighSpeed'),
        ),
    ]
