# Generated by Django 2.2.3 on 2019-07-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_auto_20190712_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorinfo',
            name='current_vs_torque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.CurrentVsTorque'),
        ),
    ]
