# Generated by Django 2.2.3 on 2019-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_motorinfo_current_vs_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvstorque',
            name='rotate_direction',
            field=models.CharField(choices=[('Positive', '正转'), ('Negitive', '反转')], max_length=32),
        ),
    ]
