# Generated by Django 2.2.3 on 2019-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20190712_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvstorque',
            name='cooling_flow',
            field=models.FloatField(default='20'),
            preserve_default=False,
        ),
    ]
