# Generated by Django 2.2.3 on 2019-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_currentvstorque_cooling_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvstorque',
            name='max_current_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
