# Generated by Django 2.2.3 on 2019-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_auto_20190712_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvstorque',
            name='cooling_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentvstorque',
            name='winding_temperature_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentvstorque',
            name='winding_temperature_min',
            field=models.FloatField(),
        ),
    ]
