# Generated by Django 2.2.3 on 2019-07-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20190712_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorinfo',
            name='current_vs_torque',
        ),
        migrations.RemoveField(
            model_name='motorinfo',
            name='highspeed',
        ),
        migrations.AddField(
            model_name='currentvstorque',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='highspeed',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='inverter_serial',
            field=models.CharField(default='170', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorinfo',
            name='motor_PN_mode_code',
            field=models.CharField(default='11', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='motor_model',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_vs_torque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.CurrentVsTorque')),
                ('highspeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.HighSpeed')),
                ('motorinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo')),
            ],
        ),
    ]
