# Generated by Django 2.2.3 on 2019-07-16 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_auto_20190716_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motor',
            options={'ordering': ['c_time'], 'verbose_name': '电机', 'verbose_name_plural': '电机汇总'},
        ),
        migrations.AddField(
            model_name='motor',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='motor',
            name='current_vs_torque',
        ),
        migrations.AddField(
            model_name='motor',
            name='current_vs_torque',
            field=models.ManyToManyField(to='test_app.CurrentVsTorque'),
        ),
        migrations.RemoveField(
            model_name='motor',
            name='highspeed',
        ),
        migrations.AddField(
            model_name='motor',
            name='highspeed',
            field=models.ManyToManyField(to='test_app.HighSpeed'),
        ),
    ]
