# Generated by Django 2.2.3 on 2019-07-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_auto_20190716_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentvstorque',
            options={'ordering': ['-c_time'], 'verbose_name': '电特性试验', 'verbose_name_plural': '电特性试验'},
        ),
        migrations.AlterModelOptions(
            name='highspeed',
            options={'ordering': ['-c_time'], 'verbose_name': '高转速试验', 'verbose_name_plural': '高转速试验'},
        ),
        migrations.AlterModelOptions(
            name='motor',
            options={'ordering': ['-c_time'], 'verbose_name': '电机', 'verbose_name_plural': '电机数据关系集'},
        ),
        migrations.AlterModelOptions(
            name='motorinfo',
            options={'ordering': ['-c_time'], 'verbose_name': '电机信息', 'verbose_name_plural': '电机信息'},
        ),
        migrations.RenameField(
            model_name='motorinfo',
            old_name='motor_PN_mode_code',
            new_name='motor_index',
        ),
    ]
