# Generated by Django 2.2.3 on 2019-07-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_auto_20190716_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='motorinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo'),
        ),
    ]
