# Generated by Django 2.2.3 on 2019-07-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_auto_20190716_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorinfo',
            name='motor_index',
        ),
    ]
