# Generated by Django 2.2.3 on 2019-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_remove_motorinfo_motor_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='highspeed',
            name='rotate_direction',
            field=models.CharField(choices=[('Positive', '正转'), ('Negitive', '反转')], default='Positive', max_length=32),
            preserve_default=False,
        ),
    ]
