# Generated by Django 2.2.3 on 2019-07-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0022_highspeed_cooling_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='highspeed',
        ),
        migrations.AddField(
            model_name='motor',
            name='highspeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highspeed', to='test_app.HighSpeed'),
        ),
    ]
