# Generated by Django 2.2.3 on 2019-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_auto_20190717_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='current_vs_torque',
            field=models.ManyToManyField(null=True, to='test_app.CurrentVsTorque'),
        ),
    ]
