# Generated by Django 2.2.3 on 2019-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0024_auto_20190717_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='current_vs_torque',
            field=models.ManyToManyField(to='test_app.CurrentVsTorque'),
        ),
    ]
