# Generated by Django 2.2.3 on 2019-07-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_auto_20190717_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='highspeed',
            name='motorinfo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='motorinfo', to='test_app.MotorInfo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
    ]
