# Generated by Django 2.2.3 on 2019-07-18 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0026_auto_20190718_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highspeed',
            name='motorinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo'),
        ),
    ]
