# Generated by Django 2.2.3 on 2019-07-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190709_1348'),
        ('test_app', '0028_auto_20190718_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorinfo',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.User'),
        ),
    ]
