# Generated by Django 2.2.3 on 2019-07-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0030_auto_20190718_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorinfo',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.User'),
        ),
    ]
