# Generated by Django 2.2.3 on 2019-08-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0031_auto_20190718_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvstorque',
            name='motorinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo'),
            preserve_default=False,
        ),
    ]
