# Generated by Django 2.2.3 on 2019-08-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0032_currentvstorque_motorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_point', models.IntegerField()),
                ('cooling_temperature', models.FloatField()),
                ('winding_temperature_min', models.FloatField()),
                ('winding_temperature_max', models.FloatField()),
                ('env_temperature', models.FloatField()),
                ('env_humidity', models.FloatField()),
                ('rotate_direction', models.CharField(choices=[('Positive', '正转'), ('Negitive', '反转')], max_length=32)),
                ('u_phase_current', models.FloatField()),
                ('v_phase_current', models.FloatField()),
                ('w_phase_current', models.FloatField()),
                ('average_phase_current', models.FloatField()),
                ('deviation', models.FloatField()),
                ('u_phase_f_current', models.FloatField()),
                ('v_phase_f_current', models.FloatField()),
                ('w_phase_f_current', models.FloatField()),
                ('average_phase_f_current', models.FloatField()),
                ('f_deviation', models.FloatField()),
                ('torque_command', models.FloatField()),
                ('torque_measured', models.FloatField()),
                ('temperature_measured', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('motorinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MotorInfo')),
            ],
            options={
                'verbose_name': '短路试验',
                'verbose_name_plural': '短路试验',
                'ordering': ['-c_time'],
            },
        ),
    ]
