# Generated by Django 2.2.3 on 2019-08-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0035_insulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulation',
            old_name='resistance_30s',
            new_name='resistance_60s',
        ),
    ]
