# Generated by Django 2.2.3 on 2019-08-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0038_calibration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calibration',
            new_name='BEMF',
        ),
    ]
