# Generated by Django 2.2.3 on 2019-08-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0040_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Stator_Resistance_EEPROM_x_10000',
            field=models.IntegerField(default=230),
            preserve_default=False,
        ),
    ]
