# Generated by Django 2.2.3 on 2019-08-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0041_calibration_stator_resistance_eeprom_x_10000'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Gamma_Ajust_x_10',
            field=models.IntegerField(default=-1338),
            preserve_default=False,
        ),
    ]
