# Generated by Django 2.2.3 on 2019-08-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0044_highspeed_cooling_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcircuit',
            name='torque_command',
        ),
    ]
