# Generated by Django 2.2.3 on 2019-08-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0045_remove_shortcircuit_torque_command'),
    ]

    operations = [
    ]
